# -*- coding: utf-8 -*-
"""Covid Aceh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qj9BTuy9a2SB-mYHzGAHAm0b4Fg9IxsS
"""

# Mengakses API covid19.go.id

import requests
resp = requests.get('https://data.covid19.go.id/public/api/update.json')

print(resp)
print(resp.headers)

# Mengekstrak Isi Respon

cov_id_raw = resp.json()

print(cov_id_raw)

# Mengekstrak Isi Respon 2

print('Length of cov_id_raw : %d.' %len(cov_id_raw))
print('Komponen cov_id_raw  : %s.' %cov_id_raw.keys())
cov_id_update = cov_id_raw['update']

# Analisa Data

print('Tanggal pembaharuan data penambahan kasus :', cov_id_update['penambahan']['tanggal'])
print('Jumlah penambahan kasus sembuh :', cov_id_update['penambahan']['jumlah_sembuh'])
print('Jumlah penambahan kasus meninggal :', cov_id_update['penambahan']['jumlah_meninggal'])
print('Jumlah total kasus positif hingga saat ini :', cov_id_update['total']['jumlah_positif'])
print('Jumlah total kasus meninggal hingga saat ini:', cov_id_update['total']['jumlah_meninggal'])

# Data Aceh

import requests
resp_aceh = requests.get('https://data.covid19.go.id/public/api/prov_detail_ACEH.json')
cov_aceh_raw = resp_aceh.json()

print(cov_aceh_raw)

# Memahami Kasus COVID-19 di Aceh

print('Nama-nama elemen utama:\n', cov_aceh_raw.keys())
print('\nUpdate terakhir : %s' %cov_aceh_raw['last_date'])
print('Jumlah total kasus COVID-19 di Aceh : %d' %cov_aceh_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Aceh : %f.2%%' %cov_aceh_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Aceh : %f.2%%' %cov_aceh_raw['sembuh_persen'])

# Memperoleh Informasi yang Lebih Lengkap

import numpy as np
import pandas as pd
cov_aceh = pd.DataFrame(cov_aceh_raw['list_perkembangan'])
print('Info cov_aceh:\n', cov_aceh.info())
print('\nLima data teratas cov_aceh:\n', cov_aceh.head())

# Menjinakkan Data
cov_aceh_tidy = (cov_aceh.drop(columns=[item for item in cov_aceh.columns
if item.startswith('AKUMULASI')
or item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_aceh_tidy['tanggal'] = pd.to_datetime(cov_aceh_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_aceh_tidy.head())

# Visualization

import matplotlib.pyplot as plt

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_aceh_tidy, x='tanggal', height='kasus_baru')
plt.show()

# Informasi pada Grafik

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_aceh_tidy, x='tanggal', height='kasus_baru', color='#FB9300')
fig.suptitle('Kasus Harian Positif COVID-19 di Aceh\n',
y=1.00, fontsize=16, fontweight='bold', ha='center')
ax.set_xlabel('')
ax.set_ylabel('Jumlah kasus')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Grafik untuk Kasus Sembuh

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_aceh_tidy, x='tanggal', height='sembuh', color='#185ADB')
ax.set_title('Kasus Harian Sembuh Dari COVID-19 di Aceh',
fontsize=22)
ax.set_xlabel('')
ax.set_ylabel('Jumlah kasus')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Grafik untuk Kasus Meninggal

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_aceh_tidy, x='tanggal', height='meninggal', color='black')
ax.set_title('Kasus Harian Meninggal Dari COVID-19 di Aceh',
fontsize=22)
ax.set_xlabel('')
ax.set_ylabel('Jumlah kasus')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Apakah Pekan ini Lebih Baik?

cov_aceh_pekanan = (cov_aceh_tidy.set_index('tanggal')['kasus_baru']
.resample('W')
.sum()
.reset_index()
.rename(columns={'kasus_baru': 'jumlah'})
)
cov_aceh_pekanan['tahun'] = cov_aceh_pekanan['tanggal'].apply(lambda x: x.year)
cov_aceh_pekanan['pekan_ke'] = cov_aceh_pekanan['tanggal'].apply(lambda x: x.weekofyear)
cov_aceh_pekanan = cov_aceh_pekanan[['tahun', 'pekan_ke', 'jumlah']]

print('Info cov_aceh_pekanan:')
print(cov_aceh_pekanan.info())
print('\nLima data teratas cov_aceh_pekanan:\n', cov_aceh_pekanan.head())

cov_aceh_pekanan['jumlah_pekanlalu'] = cov_aceh_pekanan['jumlah'].shift().replace(np.nan, 0).astype(np.int)
cov_aceh_pekanan['lebih_baik'] = cov_aceh_pekanan['jumlah'] < cov_aceh_pekanan['jumlah_pekanlalu']

print('Sepuluh data teratas:\n', cov_aceh_pekanan.head(10))

# Membuat Bar Chart

import matplotlib.pyplot as plt

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_aceh_pekanan, x='pekan_ke', height='jumlah',
color=['mediumseagreen' if x is True else 'salmon' for x in cov_aceh_pekanan['lebih_baik']])
fig.suptitle('Kasus Pekanan Positif COVID-19 di Aceh',
y=1.00, fontsize=16, fontweight='bold', ha='center')
ax.set_title('Kolom hijau menunjukan penambahan kasus baru lebih sedikit dibandingkan satu pekan sebelumnya',
fontsize=12)
ax.set_xlabel('')
ax.set_ylabel('Jumlah kasus')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Pola dan Dinamika

cov_aceh_akumulasi = cov_aceh_tidy[['tanggal']].copy()
cov_aceh_akumulasi['akumulasi_aktif'] = (cov_aceh_tidy['kasus_baru'] - cov_aceh_tidy['sembuh'] - cov_aceh_tidy['meninggal']).cumsum()
cov_aceh_akumulasi['akumulasi_sembuh'] = cov_aceh_tidy['sembuh'].cumsum()
cov_aceh_akumulasi['akumulasi_meninggal'] = cov_aceh_tidy['meninggal'].cumsum()
cov_aceh_akumulasi.tail()

# Membuat Line Chart


import matplotlib.pyplot as plt
import matplotlib.dates as mdates

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.plot('tanggal', 'akumulasi_aktif', data=cov_aceh_akumulasi, lw=2)

ax.set_title('Akumulasi aktif COVID-19 di Aceh',
fontsize=22)
ax.set_xlabel('')
ax.set_ylabel('Akumulasi aktif')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid()
plt.tight_layout()
plt.show()

# Kabar Buruk dan Kabar Baik
# Menggunakan data frame cov_aceh_akumulasi, kemudian langsung melakukan line plot dan memilih warna garis yang sesuai untuk membedakan; atau
# Menggunakan ax.plot() dan mengisikan kolom-kolom yang masing-masingnya menjadi x dan y dengan data=cov_aceh_akumulasi, dan kemudian menset warna berbeda untuk ketiga line plot.

# Langkah 1
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
cov_aceh_akumulasi.plot(x='tanggal', kind='line', ax=ax, lw=3,
color=['salmon', 'slategrey', 'olivedrab'])

ax.set_title('Dinamika Kasus COVID-19 di Aceh',
fontsize=22)
ax.set_xlabel('')
ax.set_ylabel('Akumulasi aktif')
ax.text(1, -0.1, 'Sumber data: covid.19.go.id', color='blue',
ha='right', transform=ax.transAxes)

ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b'))

plt.grid()
plt.tight_layout()
plt.show()